### ISSUE TITLE
Gambatte is saving into the roms directory

### ISSUE THREAD

**Issue by XargonWan** [XargonWan/RG-350-M-Unified-Save-folder#4]
Gambatte (Color, gambatte.opk) is saving into the rom directory, any way to fix this?

**Comment by XargonWan** [comment]
Submitted issue to Gambatte developer: https://github.com/bardeci/gambatte-dms/issues/12

**Comment by bardeci** [comment]
As i replied in my repo, gambatte.opk is an old and obsolete port.
You can fix your issue by just deleting gambatte.opk and never using it again. Use my port of gambatte for both GB and GBC.

**Comment by XargonWan** [comment]
The new Gambatte is saving into the save folder, now I can redirect it.
